const express = require('express');
const router = express.Router();
const usersController = require('../app/controllers/UserController');
router.get('/signin', usersController.signIn);
router.get('/signup', usersController.signUp);
router.get('/profile', usersController.profile);
router.get('/accountbank', usersController.accountBank);
router.get('/accountme', usersController.accountMe);
router.get('/accountsavebank', usersController.accountSaveBank);
router.get('/transhis', usersController.transactionHistory);
router.get('/accountsave', usersController.accountSave);
router.get('/accountsaveme', usersController.accountSaveMe);
module.exports = router;
